# This is a basic workflow to help you get started with Actions

name: water

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: install dependencies
        run: sudo apt-get install libcurl4-openssl-dev libgeos-dev libudunits2-dev

    # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("jsonlite",dependencies = T)'
        
    # Run R script
      - name: get_water_quality
        run: Rscript get_water_quality.R
    
    # Add new files in data folder, commit along with other modified files, push
      - name: push the water_quality_data to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add water_quality_data
          git commit -am "GH ACTION water quality $(date)"
          git push https://${{github.actor}}:${{secrets.LERY}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
        
        # Run R script
      - name: get_hydrological
        run: Rscript get_hydrological.R
      
 # Add new files in data folder, commit along with other modified files, push
      - name: push the hydrological_data to GitHub
        run: |
         git config --local user.email ly_ding@126.com
         git config --local user.name Otoliths
         git add hydrological_data
         git commit -am "GH ACTION hydrological $(date)"
         git push https://${{github.actor}}:${{secrets.LERY}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
        
        
        
